// src/ref_views/app/terminal/index.vue
<template>
  <div class="terminal code-font" @click.self="focusInput">
    <p>> Enjoy the fake terminal 😆. And there have an Easter Egg.</p>
    <div v-for="item in cmds">
      <b class="header" v-if="item[0] === 'cmd'"
        >[user@manjaro <span>{{ item[2] }}</span
        >]$</b
      >
      <span class="content" :class="item[0]" v-html="item[1]"></span>
    </div>
    <div>
      <b class="header"
        >[user@manjaro <span>{{ dirStr }}</span
        >]$</b
      >
      <input
        ref="input"
        class="code-font"
        v-model.trim="input"
        @keydown.up.prevent="upCmd"
        @keydown.down.prevent="downCmd"
        @keydown.enter="processCmd"
        @keydown.tab.prevent="autoComplete"
      />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, inject, Ref } from "vue";
import { escapeHtml, openApp } from "../../../utils/utils";
import mixin from "../../../utils/mixin";
import { typeFile, dolphinFiles } from "../../../../filesystem";

const helps = [
  ["ls", "list files or folders"],
  ["cd <dir>", "change current directory to dir"],
  ["clear", "clear screen"],
  ["pwd", "print work directory"],
  ["xdg-open <file>", "open a file"],
  ["poweroff", "close manjaro"],
  ["reboot", "reboot manjaro"],
];

export default defineComponent({
  name: "index",
  data() {
    return {
      dir: [],
      input: "",
      cmds: [],
      history: [],
      hisIdx: -1,

      dolphinFiles,
    };
  },
  mixins: [mixin],
  computed: {
    cmdLis(): Array<string> {
      return this.input.split(/\s+/);
    },
    filesNow(): Array<typeFile> {
      let idx = 0;
      let parent = this.dolphinFiles;
      while (idx < this.dir.length) {
        parent = parent.find((v) => v.name === this.dir[idx]).sub;
        idx++;
      }
      return parent;
    },
    dirsNow(): Array<typeFile> {
      return this.filesNow.filter((v) => v.isDir);
    },
    notDirsNow(): Array<typeFile> {
      return this.filesNow.filter((v) => !v.isDir);
    },
    dirStr(): string {
      return this.dir.length ? this.dir.join("/") : "~";
    },
  },
  watch: {
    cmds: {
      deep: true,
      handler() {
        if (!this.$el) return;
        this.$nextTick(() => {
          this.$el.scrollTop = this.$el.scrollHeight + 100;
        });
      },
    },
  },
  setup() {
    return {
      power: inject("power") as Ref,
    };
  },
  mounted() {
    this.$el.querySelector("input").focus();
  },
  methods: {
    focusInput() {
      this.$refs.input.focus();
    },
    pushCmd(cmd: string) {
      this.cmds.push(["cmd", cmd, this.dirStr]);
    },
    processCmd() {
      if (this.input !== "") {
        this.history.push(this.input);
      }
      this.hisIdx = -1;
      switch (this.cmdLis[0]) {
        case "":
          this.pushCmd("");
          break;
        case "help":
          this.pushCmd(this.input);
          this.cmds.push([
            "out",
            helps
              .map((v) => `<p>${escapeHtml(v[0])}</p>${escapeHtml(v[1])}\n`)
              .join(""),
          ]);
          break;
        case "ls":
          this.pushCmd(this.input);
          this.cmds.push([
            "out",
            this.filesNow
              .map((v) => (v.isDir ? `<span>${v.name}</span>` : v.name))
              .join("\n"),
          ]);
          break;
        case "poweroff":
          this.power = "shutdown";
          break;
        case "reboot":
          this.power = "reboot";
          break;
        case "cd":
          this.pushCmd(this.input);
          if (this.cmdLis.length > 2) {
            this.cmds.push(["out", 'command "cd" only take one argument']);
          } else {
            const dir = this.cmdLis[1];
            // Todo: support '/'
            if (dir && dir.includes("/")) {
              this.cmds.push(["out", "No support for multiple dir currently"]);
              break;
            }
            switch (dir) {
              case undefined:
              case "~":
                this.dir = [];
                break;
              case "..":
                if (this.dir.length > 0) this.dir.pop();
                break;
              case ".":
                break;
              default:
                if (this.dirsNow.find((v) => v.name === dir)) {
                  this.dir.push(dir);
                } else {
                  this.cmds.push(["out", "Unknown folder: " + dir]);
                }
                break;
            }
          }
          break;
        case "clear":
          this.cmds = [];
          break;
        case "pwd":
          this.pushCmd(this.input);
          this.cmds.push(["out", this.dirStr]);
          break;
        case "I":
          this.pushCmd(this.input);
          if (
            this.cmdLis.length === 3 &&
            ["like", "love"].includes(this.cmdLis[1]) &&
            ["you", "u"].includes(this.cmdLis[2])
          ) {
            this.pushCmd(this.input);
            this.cmds.push([
              "out",
              `<a style="color: #ff7474">I ${this.cmdLis[1]} ${this.cmdLis[2]} too.😽</a>`,
            ]);
          } else {
            this.cmds.push(["out", 'Unknown command: "' + this.input + '"']);
          }
          break;
        case "xdg-open":
          this.pushCmd(this.input);
          if (this.cmdLis.length > 2) {
            this.cmds.push([
              "out",
              'command "xdg-open" only take one argument',
            ]);
          } else {
            if (this.cmdLis[1]) {
              const file = this.filesNow.find(
                (v) => !v.isDir && v.name === this.cmdLis[1],
              );
              if (file) {
                const mime1 = file.mime.split("/")[0];
                switch (file.mime) {
                  case "text/markdown":
                    openApp.call(this, "gedit").params.filepath.value = this.dir
                      .concat([file.name])
                      .join("/");
                    break;
                  case "audio/mpeg":
                    openApp.call(this, "music").params.filepath.value = this.dir
                      .concat([file.name])
                      .join("/");
                    break;
                  default:
                    if (mime1 === "image") {
                      openApp.call(this, "image viewer").params.filepath.value =
                        this.dir.concat([file.name]).join("/");
                    }
                    break;
                }
              } else {
                this.cmds.push([
                  "out",
                  'No such file: "' + this.cmdLis[1] + '"',
                ]);
              }
            }
          }
          break;
        default:
          this.pushCmd(this.input);
          this.cmds.push(["out", 'Unknown command: "' + this.input + '"']);
          break;
      }
      this.input = "";
    },
    autoComplete() {
      const command = this.cmdLis[0];
      if (!command) {
        this.pushCmd("");
        this.cmds.push(["out", 'type "help" to see helps']);
        this.input = "";
      } else if (command === "cd") {
        const needComplete = this.cmdLis[1];
        const dirs = [];
        if (needComplete) {
          for (const d of this.dirsNow) {
            if (
              d.name.length >= needComplete.length &&
              d.name.startsWith(needComplete)
            ) {
              dirs.push(d.name);
            }
          }
        } else {
          dirs.push(...this.dirsNow.map((v) => v.name));
        }
        if (dirs.length > 0) {
          if (dirs.length === 1) {
            this.input = "cd " + dirs[0];
          } else {
            this.pushCmd(this.input);
            this.cmds.push(["out", dirs.join("\t")]);
          }
        }
      } else if (command === "xdg-open") {
        const needComplete = this.cmdLis[1];
        const dirs = [];
        if (needComplete) {
          for (const d of this.notDirsNow) {
            if (
              d.name.length >= needComplete.length &&
              d.name.startsWith(needComplete)
            ) {
              dirs.push(d.name);
            }
          }
        } else {
          dirs.push(...this.notDirsNow.map((v) => v.name));
        }
        if (dirs.length > 0) {
          if (dirs.length === 1) {
            this.input = "xdg-open " + dirs[0];
          } else {
            this.pushCmd(this.input);
            this.cmds.push(["out", dirs.join("\t")]);
          }
        }
      } else if (this.cmdLis.length === 1) {
        if (command === "c") {
          this.pushCmd("");
          this.cmds.push(["out", "cd\tclear"]);
        } else if (command === "p") {
          this.pushCmd("");
          this.cmds.push(["out", "poweroff\tpwd"]);
        } else if (["h", "he", "hel", "help"].includes(command)) {
          this.input = "help ";
        } else if (["l", "ls"].includes(command)) {
          this.input = "ls ";
        } else if (["cl", "cle", "clea", "clear"].includes(command)) {
          this.input = "clear ";
        } else if (["pw", "pwd"].includes(command)) {
          this.input = "pwd ";
        } else if (command === "cd") {
          const needComplete = this.cmdLis[1];
          console.log(needComplete);
          if (needComplete) {
            const dirs = [];
            for (const d of this.dirsNow) {
              if (
                d.name.length >= needComplete &&
                d.name.startsWith(needComplete)
              ) {
                dirs.push(d.name);
              }
            }
            console.log(dirs);
          }
        } else if (
          ["r", "re", "reb", "rebo", "reboo", "reboot"].includes(command)
        ) {
          this.input = "reboot ";
        } else if (
          [
            "po",
            "pow",
            "powe",
            "power",
            "powero",
            "powerof",
            "poweroff",
          ].includes(command)
        ) {
          this.input = "poweroff ";
        } else if (
          [
            "x",
            "xd",
            "xdg",
            "xdg-",
            "xdg-o",
            "xdg-op",
            "xdg-ope",
            "xdg-open",
          ].includes(command)
        ) {
          this.input = "xdg-open ";
        }
      }
    },
    upCmd() {
      if (this.hisIdx === -1) {
        this.hisIdx = this.history.length - 1;
      } else if (this.hisIdx > 0) {
        this.hisIdx--;
      }
      if (this.history.length && this.hisIdx >= 0) {
        this.input = this.history[this.hisIdx];
      }
    },
    downCmd() {
      if (this.hisIdx === -1) {
        this.hisIdx = this.history.length - 1;
      } else if (this.hisIdx < this.history.length - 1) {
        this.hisIdx++;
      }
      if (this.history.length && this.hisIdx < this.history.length) {
        this.input = this.history[this.hisIdx];
      }
    },
  },
});
</script>

<style scoped lang="scss">
.terminal {
  width: 100%;
  height: 100%;
  background: #1e2229;
  font-size: 0.75rem;
  color: white;
  padding-bottom: 0.6rem;
  > p {
    padding: 0.5rem;
    font-size: 0.8rem;
  }
  > div {
    display: flex;
    align-items: center;
    padding-top: 0.4rem;
    flex-wrap: wrap;
  }
  .header {
    word-break: keep-all;
    white-space: nowrap;
    flex-shrink: 0;
    color: #59a850;
    margin: 0 0.3rem;
    > span {
      color: white;
    }
  }
  .content {
    &.cmd {
      color: #13cba8;
    }

    &.out {
      width: calc(100% - 1.2rem);
      padding: 0 0.6rem;
      white-space: pre;
      :deep(span) {
        color: #44bbff;
      }
      :deep(p) {
        display: inline-block;
        width: 7.5rem;
        color: #ffce79;
      }
    }
  }
  input {
    background: transparent;
    flex-grow: 1;
    outline: none;
    border: none;
    color: white;
    font-size: 0.75rem;
  }
}
</style>

// src/apps/Terminal.tsx
'use client';

import React, { useState, useEffect, useRef } from 'react';
import { useAppStore } from '@/store/useAppStore';
import { dolphinFiles, typeFile } from '@/data/filesystem';
import { escapeHtml } from '@/utils/utils';

// Helper for opening apps from terminal
// In Vue ref it used `openApp.call(this, ...)` which accessed the store/mixin.
// We can use the store hook.

const HELPS = [
  ["ls", "list files or folders"],
  ["cd <dir>", "change current directory to dir"],
  ["clear", "clear screen"],
  ["pwd", "print work directory"],
  ["xdg-open <file>", "open a file"],
  ["poweroff", "close manjaro"],
  ["reboot", "reboot manjaro"],
];

export const Terminal = () => {
  const { setPowerState, openApp } = useAppStore();
  const [history, setHistory] = useState<string[]>([]);
  const [cmds, setCmds] = useState<Array<[string, string, string?]>>([]); // [type, content, dirStr?]
  const [input, setInput] = useState("");
  const [dir, setDir] = useState<string[]>([]);
  const [hisIdx, setHisIdx] = useState(-1);
  const inputRef = useRef<HTMLInputElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Computed equivalents
  const cmdLis = input.trim().split(/\s+/);
  const dirStr = dir.length ? dir.join("/") : "~";

  const getFilesNow = () => {
    let idx = 0;
    let parent = dolphinFiles as typeFile[];
    // Traverse
    // Note: filesystem.ts export might need check.
    // Assuming dolphinFiles is array of roots.
    // If dir is empty, we are at root? Vue ref says:
    // while (idx < this.dir.length) { parent = parent.find... }
    // If dir is [], it returns dolphinFiles (root).
    
    let current = parent;
    for (const d of dir) {
        const found = current.find(v => v.isDir && v.name === d);
        if (found && found.sub) {
            current = found.sub;
        } else {
            return []; // Should not happen if logic is correct
        }
    }
    return current;
  };

  const filesNow = getFilesNow();
  const dirsNow = filesNow.filter(v => v.isDir);
  const notDirsNow = filesNow.filter(v => !v.isDir);

  useEffect(() => {
    if (containerRef.current) {
      containerRef.current.scrollTop = containerRef.current.scrollHeight;
    }
  }, [cmds]);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const focusInput = () => inputRef.current?.focus();

  const pushCmd = (cmd: string) => {
    setCmds(prev => [...prev, ["cmd", cmd, dirStr]]);
  };

  const processCmd = () => {
    if (input.trim() !== "") {
      setHistory(prev => [...prev, input]);
    }
    setHisIdx(-1);

    const command = cmdLis[0];
    const args = cmdLis.slice(1);
    
    pushCmd(input);

    switch (command) {
      case "":
        break;
      case "help":
        setCmds(prev => [...prev, ["out", HELPS.map(v => `<p>${escapeHtml(v[0])}</p>${escapeHtml(v[1])}\n`).join("")]]);
        break;
      case "ls":
        setCmds(prev => [...prev, ["out", filesNow.map(v => v.isDir ? `<span class="text-[#44bbff]">${v.name}</span>` : v.name).join("\n")]]);
        break;
      case "poweroff":
        setPowerState('shutdown');
        break;
      case "reboot":
        setPowerState('reboot');
        break;
      case "cd":
        if (args.length > 1) {
            setCmds(prev => [...prev, ["out", 'command "cd" only take one argument']]);
        } else {
            const target = args[0];
             if (target && target.includes("/")) {
                setCmds(prev => [...prev, ["out", "No support for multiple dir currently"]]);
             } else {
                 switch (target) {
                     case undefined:
                     case "~":
                         setDir([]);
                         break;
                     case "..":
                         setDir(prev => prev.length > 0 ? prev.slice(0, -1) : prev);
                         break;
                     case ".":
                         break;
                     default:
                         if (dirsNow.find(v => v.name === target)) {
                             setDir(prev => [...prev, target]);
                         } else {
                             setCmds(prev => [...prev, ["out", "Unknown folder: " + target]]);
                         }
                         break;
                 }
             }
        }
        break;
      case "clear":
        setCmds([]);
        return; // Return early to avoid clearing being overwritten or weird state? No, setCmds([]) clears it.
        // Wait, pushCmd was called before switch. So the command "clear" is added, then cleared immediately. 
        // Logic in Vue: this.cmds = []; (clears everything).
        // React: setCmds([]) will clear.
        // But pushCmd uses callback... wait.
        // pushCmd calls setCmds(prev => ...).
        // setCmds([]) calls setCmds.
        // React batches. If I call setCmds twice, the second one might overwrite or they might conflict if I don't be careful.
        // Better to not pushCmd if clear? Or just clear.
        break;
      case "pwd":
        setCmds(prev => [...prev, ["out", dirStr]]);
        break;
      case "xdg-open":
        if (args.length !== 1) {
             setCmds(prev => [...prev, ["out", 'command "xdg-open" only take one argument']]);
        } else {
            const fileName = args[0];
            const file = filesNow.find(v => !v.isDir && v.name === fileName);
            if (file) {
                 // Logic to open app
                 // mime type check
                 // For now, simplify mapping
                 // Vue ref: text/markdown -> gedit, audio/mpeg -> music, image/* -> image viewer
                 // And passes filepath param.
                 const path = dir.concat([file.name]).join("/");
                 const mime = file.mime;
                 
                 if (mime === "text/markdown") {
                     openApp("gedit", { filepath: path });
                 } else if (mime === "audio/mpeg") {
                     openApp("music", { filepath: path });
                 } else if (mime.startsWith("image/")) {
                     openApp("image viewer", { filepath: path });
                 } else {
                     setCmds(prev => [...prev, ["out", `Cannot open file type: ${mime}`]]);
                 }
            } else {
                setCmds(prev => [...prev, ["out", 'No such file: "' + fileName + '"']]);
            }
        }
        break;
      default:
         setCmds(prev => [...prev, ["out", 'Unknown command: "' + input + '"']]);
         break;
    }
    
    setInput("");
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
        e.preventDefault();
        processCmd();
    } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        if (hisIdx === -1) {
            if (history.length > 0) {
                setHisIdx(history.length - 1);
                setInput(history[history.length - 1]);
            }
        } else if (hisIdx > 0) {
            setHisIdx(prev => prev - 1);
            setInput(history[hisIdx - 1]);
        }
    } else if (e.key === 'ArrowDown') {
        e.preventDefault();
        if (hisIdx !== -1) {
             if (hisIdx < history.length - 1) {
                 setHisIdx(prev => prev + 1);
                 setInput(history[hisIdx + 1]);
             } else {
                 setHisIdx(-1);
                 setInput("");
             }
        }
    } else if (e.key === 'Tab') {
        e.preventDefault();
        // Auto complete logic
        const command = cmdLis[0];
        if (!command) {
             // help hint
        } else if (command === 'cd') {
             const partial = cmdLis[1] || "";
             const matches = dirsNow.filter(d => d.name.startsWith(partial));
             if (matches.length === 1) {
                 setInput(`cd ${matches[0].name}`);
             } else if (matches.length > 1) {
                 // show options? 
                 // In Vue it appends to cmds.
                 pushCmd(input);
                 setCmds(prev => [...prev, ["out", matches.map(m => m.name).join("\t")]]);
             }
        }
        // ... more autocomplete logic could be added
    }
  };

  return (
    <div 
      className="w-full h-full bg-[#1e2229] text-white p-2 font-mono text-xs overflow-auto" 
      onClick={focusInput}
      ref={containerRef}
    >
      <p className="p-2 text-[0.8rem]">{'> Enjoy the fake terminal 😆. And there have an Easter Egg.'}</p>
      
      {cmds.map((item, idx) => (
        <div key={idx} className="flex flex-wrap items-center pt-1">
          {item[0] === 'cmd' && (
             <b className="whitespace-nowrap shrink-0 text-[#59a850] mr-1.5">
               [user@manjaro <span className="text-white">{item[2]}</span>]$
             </b>
          )}
          <span 
            className={`whitespace-pre-wrap break-all ${item[0] === 'cmd' ? 'text-[#13cba8]' : 'w-[calc(100%-1.2rem)] px-2'}`}
            dangerouslySetInnerHTML={{ __html: item[1] }} 
          />
        </div>
      ))}

      <div className="flex items-center pt-1">
        <b className="whitespace-nowrap shrink-0 text-[#59a850] mr-1.5">
           [user@manjaro <span className="text-white">{dirStr}</span>]$
        </b>
        <input
          ref={inputRef}
          className="bg-transparent grow outline-none border-none text-white font-mono text-xs"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          autoComplete="off"
        />
      </div>
    </div>
  );
};
