// src/ref_views/desktop/index.vue
<template>
  <section>
    <img draggable="false" :src="wallpaper" alt="wallpaper" />
    <window
      v-for="app in apps"
      @resize="proxyResize('app-' + app.name)"
      @move="proxyMove('app-' + app.name, $event)"
      class="app"
      v-show="app.status.value > 0"
      :app="app"
    >
      <component
        :ref="'app-' + app.name"
        :is="app.app"
        v-if="app.status.value > 0"
      ></component>
    </window>
  </section>
</template>

<script lang="ts">
import { defineComponent, inject } from "vue";
import wallpaper from "../../assets/images/wallpaper.png";
import Window from "../../components/window.vue";
import { typeApp } from "../../utils/apps";

export default defineComponent({
  name: "index",
  components: { Window },
  data() {
    return {
      wallpaper,
    };
  },
  setup() {
    return {
      apps: inject("apps") as Array<typeApp>,
    };
  },
  methods: {
    proxyResize(app) {
      if (this.$refs[app] && this.$refs[app].windowResize) {
        this.$refs[app].windowResize();
      }
    },
    proxyMove(app, e) {
      if (this.$refs[app] && this.$refs[app].windowMove) {
        this.$refs[app].windowMove(e);
      }
    },
  },
});
</script>

<style scoped lang="scss">
section {
  width: 100%;
  height: calc(100% - 3.2rem);
  position: relative;
  overflow: hidden;
  > img {
    object-fit: cover;
    width: 100vw;
    height: 100vh;
    user-select: none;
    pointer-events: none;
    position: absolute;
    left: 0;
    right: 0;
  }
}
</style>

// src/components/Desktop.tsx
'use client';

import { useAppStore } from '@/store/useAppStore';
import { Window } from './Window';
import { basePath } from '@/utils/utils';
import Image from 'next/image';

export const Desktop = () => {
  const { apps } = useAppStore();

  return (
    <div className="relative w-screen h-[calc(100vh-3.2rem)] overflow-hidden">
      <Image
        src={`${basePath}/assets/images/wallpaper.png`}
        alt="wallpaper"
        fill
        className="object-cover pointer-events-none select-none -z-10"
        priority
      />
      {apps.map((app) => (
        <Window key={app.name} app={app} />
      ))}
    </div>
  );
};
