// src/ref_views/taskbar/index.vue
<template>
  <section class="flex" id="taskbar">
    <i @click="toggleLeftMenu" class="icon-menu flex"
      ><svg-icon name="plasma"
    /></i>
    <div class="pinned flex">
      <app-icon
        v-for="app in pinnedApp"
        :class="'_item-' + app.name"
        :app="app"
      />
    </div>
    <div class="apps flex">
      <app-icon
        v-for="app in otherApp"
        :class="'_item-' + app.name"
        :app="app"
      />
    </div>

    <div class="pendant flex" :class="{ active: showRight === 'arrow' }">
      <i
        :class="{ active: showRight === 'paste' }"
        @click="toggleRightMenu('paste')"
      >
        <svg-icon name="paste" />
      </i>
      <i
        @click="
          keyboardType =
            keyboardType === 'keyboard' ? 'google-pinyin' : 'keyboard'
        "
      >
        <svg-icon :name="keyboardType" />
      </i>
      <i
        :class="{ active: showRight === 'volume' }"
        @click="toggleRightMenu('volume')"
      >
        <svg-icon name="audio-volume-muted" />
      </i>
      <i
        :class="{ active: showRight === 'bluetooth' }"
        @click="toggleRightMenu('bluetooth')"
      >
        <svg-icon name="bluetooth" />
      </i>
      <i
        :class="{ active: showRight === 'wifi' }"
        @click="toggleRightMenu('wifi')"
      >
        <svg-icon name="wifi" />
      </i>
      <i
        :class="{ toggled: showRight === 'arrow' }"
        @click="toggleRightMenu('arrow')"
        class="trans"
      >
        <svg-icon
          name="triangle"
          style="width: 1.1rem; height: 1.1rem; transform: rotate(-90deg)"
        />
      </i>
      <i @click="showDesktop">
        <svg-icon name="desktop" style="width: 2.2rem; height: 2.2rem" />
      </i>
      <div class="time flex" @click="toggleCalendar">
        <time>{{ time }}</time>
        <span>{{ date }}</span>
      </div>
    </div>

    <left-menu ref="leftmenu" :show="showLeft" @focusout="leftFocusout" />
    <right-menu :show="showRight" @focusout="rightFocusout" />
    <the-calendar
      ref="calendar"
      :show="showCalendar"
      @focusout="calendarFocusout"
    />
    <span class="bg"></span>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import AppIcon from "./appIcon.vue";
import leftMenu from "./leftMenu.vue";
import rightMenu from "./rightMenu.vue";
import TheCalendar from "./calendar.vue";
import dayjs, { Dayjs } from "dayjs";
import { typeApp } from "../../utils/apps";
import mixin from "../../utils/mixin";

export default defineComponent({
  name: "index",
  components: { AppIcon, leftMenu, rightMenu, TheCalendar },
  data() {
    return {
      showLeft: false,
      showRight: "",
      showCalendar: false,
      oldShowRight: "",
      animation: false,

      arrowActive: false,
      keyboardType: "keyboard",
      timeStamp: dayjs(Date.now()) as Dayjs,
      showDesktopLis: [] as Array<string>,
    };
  },
  mixins: [mixin],
  computed: {
    pinnedApp(): Array<typeApp> {
      return this.apps
        .filter((app: typeApp) => app.taskbar != undefined)
        .sort((a: typeApp, b: typeApp) => a.taskbar - b.taskbar);
    },
    otherApp(): Array<typeApp> {
      return this.apps
        .filter(
          (app: typeApp) => app.order != undefined && app.status.value > 0,
        )
        .sort((a: typeApp, b: typeApp) => a.order.value - b.order.value);
    },
    time(): string {
      return this.timeStamp.format("HH:mm");
    },
    date(): string {
      return this.timeStamp.format("DD MMM");
    },
  },
  created() {
    setInterval(() => {
      this.timeStamp = dayjs(Date.now());
    }, 1000);
  },
  methods: {
    toggleLeftMenu() {
      if (this.animation) return;
      this.animation = false;
      !this.showLeft && (this.showLeft = !this.showLeft);
    },
    leftFocusout() {
      this.showLeft = false;
      this.animation = true;
      setTimeout(() => (this.animation = false), 200);
    },
    toggleRightMenu(type: string) {
      if (this.animation && this.oldShowRight === type) return;
      this.showRight = type;
    },
    rightFocusout() {
      this.oldShowRight = this.showRight;
      this.showRight = "";
      this.animation = true;
      setTimeout(() => (this.animation = false), 200);
    },
    showDesktop() {
      this.apps.map((app: typeApp) => {
        if (this.showDesktopLis.includes(app.name)) {
          app.status.value = 2;
          this.showDesktopLis.splice(
            this.showDesktopLis.indexOf(app.name) || 0,
            1,
          );
        } else if (app.status.value === 2) {
          app.status.value = 1;
          this.showDesktopLis.push(app.name);
        }
      });
    },
    toggleCalendar() {
      if (this.animation) return;
      this.showCalendar = !this.showCalendar;
      this.animation = false;
    },
    calendarFocusout() {
      this.showCalendar = false;
      this.animation = true;
      setTimeout(() => (this.animation = false), 200);
    },
  },
});
</script>

<style scoped lang="scss">
@use "src/assets/style/public" as *;

section {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  height: 3.2rem;
  box-shadow: 0 0 0.5rem #171717;
  z-index: $z-index-taskbar;
  > * {
    z-index: 3;
  }
  > span {
    position: absolute;
    background: #2b2e33;
    width: 100%;
    height: 100%;
    z-index: 2;
  }
  > .icon-menu:deep(> svg) {
    width: 2.5rem;
    height: 2.5rem;
    margin: 0 0.4rem;
    fill: white;
  }
  > .pinned {
    height: 100%;
  }
  > .apps {
    height: 100%;
  }
  .app {
    :deep(> svg) {
      transition: all 0.15s linear;
    }
    &:hover {
      :deep(> svg) {
        filter: saturate(4);
      }
    }
  }
  > .pendant {
    margin-left: auto;
    height: 100%;
    position: relative;
    &:before {
      content: "";
      position: absolute;
      width: 77%;
      height: 3px;
      background: #44bbff;
      top: 0;
      left: 0.5rem;
      opacity: 0;
      transition: opacity 0.1s linear;
    }
    &.active {
      &:before {
        opacity: 1;
      }
    }
    > i {
      height: 100%;
      display: flex;
      align-items: center;
      margin: 0 0.1rem;
      padding: 0 0.15rem;
      position: relative;
      :deep(> svg) {
        width: 1.6rem;
        height: 1.6rem;
        fill: white;
      }
      &:before {
        content: "";
        position: absolute;
        width: 80%;
        height: 3px;
        background: #44bbff;
        top: 0;
        left: 10%;
        opacity: 0;
        transition: opacity 0.1s linear;
      }
      &.active {
        &:before {
          opacity: 1;
        }
      }
      &.toggled {
        transform: rotate(180deg);
      }
    }
    > .time {
      height: 100%;
      flex-direction: column;
      color: white;
      margin: 0 0.6rem;
      justify-content: center;
      user-select: none;
      > time {
        font-size: 1.2rem;
      }
      > span {
        font-size: 0.85rem;
      }
    }
  }
}
</style>

// src/components/Taskbar.tsx
'use client';

import { useAppStore } from '@/store/useAppStore';
import { Icon } from './Icon';
import dayjs from 'dayjs';
import { useEffect, useState } from 'react';

export const Taskbar = () => {
  const { apps, openApp, bringToFront } = useAppStore();
  const [time, setTime] = useState(dayjs());

  useEffect(() => {
    const timer = setInterval(() => setTime(dayjs()), 1000);
    return () => clearInterval(timer);
  }, []);

  const pinnedApps = apps
    .filter((app) => app.taskbar !== undefined)
    .sort((a, b) => (a.taskbar || 0) - (b.taskbar || 0));

  const runningApps = apps
    .filter((app) => app.status > 0 && app.taskbar === undefined)
    .sort((a, b) => (a.order || 0) - (b.order || 0));

  const handleAppClick = (appName: string, isActive: boolean) => {
    if (isActive) {
        // If active (top), minimize? Or just bring to front if not top?
        // Logic: if top, minimize. If not top, bring to front.
        // I need to know if it's top.
        // For now, simple toggle: open if closed, bringToFront if open.
        // minimize logic is tricky without knowing if it's top.
        // Let's just open/bringToFront for now.
        const app = apps.find(a => a.name === appName);
        if (app?.status === 0) {
            openApp(appName);
        } else {
             // Toggle minimize? 
             // We'll stick to basic open/focus.
             bringToFront(appName);
        }
    } else {
      openApp(appName);
    }
  };

  return (
    <div className="fixed bottom-0 left-0 w-full h-[3.2rem] bg-[#2b2e33] flex items-center shadow-[0_0_0.5rem_#171717] z-50 text-white px-2">
      <div className="flex items-center px-2 hover:bg-white/10 h-full cursor-pointer transition-colors">
        <Icon name="plasma" size={40} className="fill-white" />
      </div>

      <div className="flex h-full mx-2 gap-1">
        {pinnedApps.map((app) => (
          <div
            key={app.name}
            className={`flex items-center justify-center px-2 h-full hover:bg-white/10 cursor-pointer transition-all border-b-2 ${
              app.status > 0 ? 'border-[#44bbff]' : 'border-transparent'
            }`}
            onClick={() => handleAppClick(app.name, app.status > 0)}
          >
            <Icon name={app.icon} size={32} />
          </div>
        ))}
      </div>

      <div className="flex h-full mx-2 gap-1">
        {runningApps.map((app) => (
            <div
            key={app.name}
            className={`flex items-center justify-center px-2 h-full hover:bg-white/10 cursor-pointer transition-all border-b-2 border-[#44bbff]`}
            onClick={() => handleAppClick(app.name, true)}
          >
            <Icon name={app.icon} size={32} />
          </div>
        ))}
      </div>

      <div className="ml-auto flex items-center h-full gap-2">
         {/* System Tray */}
         <div className="flex items-center h-full px-1 hover:bg-white/10 cursor-pointer">
             <Icon name="paste" size={20} />
         </div>
         <div className="flex items-center h-full px-1 hover:bg-white/10 cursor-pointer">
             <Icon name="keyboard" size={20} />
         </div>
         <div className="flex items-center h-full px-1 hover:bg-white/10 cursor-pointer">
             <Icon name="audio-volume-muted" size={20} />
         </div>
         <div className="flex items-center h-full px-1 hover:bg-white/10 cursor-pointer">
             <Icon name="bluetooth" size={20} />
         </div>
         <div className="flex items-center h-full px-1 hover:bg-white/10 cursor-pointer">
             <Icon name="wifi" size={20} />
         </div>
         <div className="flex items-center h-full px-1 hover:bg-white/10 cursor-pointer">
             <Icon name="triangle" size={16} style={{transform: 'rotate(-90deg)'}} />
         </div>

         {/* Desktop Peek */}
         <div className="flex items-center h-full px-2 hover:bg-white/10 cursor-pointer">
             <Icon name="desktop" size={30} />
         </div>

         {/* Clock */}
         <div className="flex flex-col items-center justify-center h-full px-3 hover:bg-white/10 cursor-pointer select-none leading-none">
             <span className="text-lg">{time.format('HH:mm')}</span>
             <span className="text-xs text-gray-400">{time.format('DD MMM')}</span>
         </div>
      </div>
    </div>
  );
};
