// src/apps/Settings.tsx
'use client';

import React, { useState } from 'react';
import { Icon } from '@/components/Icon';

const TABS = [
  { name: 'Kernel', icon: 'settings' },
  { name: 'Keyboard Settings', icon: 'settings-keyboard' },
  { name: 'Locale', icon: 'locale' },
  { name: 'Time and Date', icon: 'settings-time' },
  { name: 'User Accounts', icon: 'settings-user' },
];

export const Settings = () => {
  const [activeTab, setActiveTab] = useState('Kernel');

  return (
    <div className="flex flex-col w-full h-full text-white bg-[#262626]">
      {/* Header */}
      <div className="flex bg-[#31363b] border-b border-gray-500 w-full h-10 items-center">
        <div className="w-[30%] h-full flex items-center px-2 border-r border-gray-500">
           <input className="w-[80%] bg-zinc-700 text-white px-1 text-sm rounded outline-none" placeholder="Search..." />
        </div>
        <div className="w-[70%] h-full flex items-center px-4">
           <span className="text-lg">{activeTab}</span>
        </div>
      </div>

      {/* Body */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <div className="w-[30%] h-full border-r border-gray-500 overflow-y-auto">
          {TABS.map(tab => (
            <div
              key={tab.name}
              className={`flex items-center p-2 border-b border-gray-500/30 cursor-pointer hover:bg-[#7dcfff33] ${activeTab === tab.name ? 'bg-[#44bbff88]' : ''}`}
              onClick={() => setActiveTab(tab.name)}
            >
              <Icon name={tab.icon} size={24} className="mr-2" />
              <span className="text-sm">{tab.name}</span>
            </div>
          ))}
        </div>

        {/* Content */}
        <div className="w-[70%] h-full p-4 overflow-y-auto bg-[#262626]">
          {activeTab === 'Kernel' && (
            <div className="flex flex-col items-center w-full">
              <div className="flex flex-col items-center my-8">
                 <Icon name="manjaro" size={112} />
                 <div className="flex flex-col items-center mt-4">
                    <b className="text-2xl">Manjaro Linux</b>
                    <a href="https://manjaro.org" target="_blank" rel="noopener noreferrer" className="text-[#2980b9] text-sm mt-2 hover:underline">
                      https://manjaro.org/
                    </a>
                 </div>
              </div>

              <div className="flex flex-col gap-2 w-[80%] max-w-md">
                 <InfoRow label="KDE Plasma Version:" value="5.21.4" />
                 <InfoRow label="KDE Frameworks Version:" value="5.81.0" />
                 <InfoRow label="Qt Version:" value="5.15.2" />
                 <InfoRow label="Kernel Version:" value="5.10.34-1-MANJARO" />
                 <InfoRow label="OS Type:" value="64-bit" />
                 <InfoRow label="Graphics Platform:" value="X11" />
              </div>
            </div>
          )}
          {activeTab !== 'Kernel' && (
              <div className="flex items-center justify-center h-full text-gray-500">
                  Settings for {activeTab} not implemented.
              </div>
          )}
        </div>
      </div>
    </div>
  );
};

const InfoRow = ({ label, value }: { label: string; value: string }) => (
  <div className="flex text-sm">
    <span className="w-1/2 text-right text-gray-400 mr-4">{label}</span>
    <span className="w-1/2 text-left">{value}</span>
  </div>
);

// src/ref_views/app/settings/index.vue
<template>
  <div class="settings flex">
    <div class="head flex">
      <div class="flex">
        <input class="common" placeholder="Search..." />
      </div>
      <span>{{ activeTab }}</span>
    </div>
    <div class="body flex">
      <div class="menu">
        <div
          @click="activeTab = 'Kernel'"
          :class="{ active: activeTab === 'Kernel' }"
        >
          <svg-icon name="settings" /><span>Kernel</span>
        </div>
        <div
          @click="activeTab = 'Keyboard Settings'"
          :class="{ active: activeTab === 'Keyboard Settings' }"
        >
          <svg-icon name="settings-keyboard" /><span>Keyboard Settings</span>
        </div>
        <div
          @click="activeTab = 'Locale'"
          :class="{ active: activeTab === 'Locale' }"
        >
          <svg-icon name="locale" /><span>Locale</span>
        </div>
        <div
          @click="activeTab = 'Time and Date'"
          :class="{ active: activeTab === 'Time and Date' }"
        >
          <svg-icon name="settings-time" /><span>Time and Date</span>
        </div>
        <div
          @click="activeTab = 'User Accounts'"
          :class="{ active: activeTab === 'User Accounts' }"
        >
          <svg-icon name="settings-user" /><span>User Accounts</span>
        </div>
      </div>
      <div class="detail">
        <div v-if="activeTab === 'Kernel'" class="kernel flex">
          <div class="flex">
            <svg-icon name="manjaro" />
            <span class="flex">
              <b>Manjaro Linux</b>
              <a href="https://manjaro.org" target="_blank"
                >https://manjaro.org/</a
              >
            </span>
          </div>
          <span>
            <a>KDE Plasma Version:</a>
            <span>5.21.4</span>
          </span>
          <span>
            <a>KDE Frameworks Version:</a>
            <span>5.81.0</span>
          </span>
          <span>
            <a>Qt Version:</a>
            <span>5.15.2</span>
          </span>
          <span>
            <a>Kernel Version:</a>
            <span>5.10.34-1-MANJARO</span>
          </span>
          <span>
            <a>OS Type:</a>
            <span>64-bit</span>
          </span>
          <span>
            <a>Graphics Platform:</a>
            <span>X11</span>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
export default {
  name: "index",
  data() {
    return {
      activeTab: "Kernel",
    };
  },
};
</script>

<style scoped lang="scss">
.settings {
  width: 100%;
  height: 100%;
  color: white;
  flex-direction: column;
  > .head {
    background: #31363b;
    border-bottom: 1px solid gray;
    width: 100%;
    > div {
      padding: 0.5rem 0;
      width: 30%;
      > input {
        width: 80%;
      }
      border-right: 1px solid gray;
    }
    > span {
      width: calc(70% - 1rem);
      padding-left: 1rem;
      font-size: 1.25rem;
    }
  }
  > .body {
    width: 100%;
    flex-grow: 1;
    > .menu {
      width: 30%;
      height: 100%;
      border-right: 1px solid gray;
      > div {
        padding: 0.4rem 0;
        border-bottom: 1px solid rgba(94, 77, 77, 0.3);
        display: flex;
        align-items: center;
        &.active {
          background: #44bbff88;
        }
        &:not(.active):hover {
          background: #7dcfff33;
        }
        :deep(> svg) {
          margin: 0 0.4rem;
          width: 1.5rem;
          height: 1.5rem;
        }

        > span {
          font-size: 0.8rem;
        }
      }
    }
    > .detail {
      width: 70%;
      height: 100%;
      > .kernel {
        width: 100%;
        flex-direction: column;
        > div {
          justify-content: center;
          margin: 2rem 0;
          :deep(> svg) {
            width: 7rem;
            height: 7rem;
          }
          > span {
            margin-left: 1rem;
            flex-direction: column;
            > b {
              font-size: 1.5rem;
            }
            > a {
              margin-top: 0.5rem;
              color: #2980b9;
              font-size: 0.9rem;
            }
          }
        }
        > span {
          width: 20rem;
          font-size: 0.84rem;
          margin-bottom: 0.6rem;
          display: flex;
          align-items: center;
          > a {
            width: 10rem;
            text-align: right;
            white-space: nowrap;
          }
          > span {
            margin-left: 0.5rem;
          }
        }
      }
    }
  }
}
</style>
