// src/components/taskbar/Taskbar.tsx
import { useDesktopStore } from '@/store/useDesktopStore';
import { Icon } from '@/components/Icon';
import clsx from 'clsx';
import dayjs from 'dayjs';
import { useEffect, useState } from 'react';
import { StartMenu } from './StartMenu';
import { SystemTrayPopup } from './SystemTrayPopup';
import { CalendarWidget } from './CalendarWidget';

export const Taskbar = () => {
  const { apps, openApp, minimizeApp, activeAppId, activeMenu, setActiveMenu } = useDesktopStore();
  const [time, setTime] = useState(dayjs());

  useEffect(() => {
    const timer = setInterval(() => setTime(dayjs()), 1000);
    return () => clearInterval(timer);
  }, []);

  const pinnedApps = apps.filter(app => app.isPinned).sort((a, b) => (a.priority || 0) - (b.priority || 0));
  const runningUnpinnedApps = apps.filter(app => !app.isPinned && app.isOpen);

  const handleAppClick = (id: string, isOpen: boolean, isMinimized: boolean) => {
    if (isOpen && !isMinimized && activeAppId === id) {
      minimizeApp(id);
    } else {
      openApp(id);
    }
    setActiveMenu(null);
  };

  const toggleMenu = (menu: typeof activeMenu) => {
    if (activeMenu === menu) {
        setActiveMenu(null);
    } else {
        setActiveMenu(menu);
    }
  };

  const getTrayView = () => {
      if (activeMenu?.startsWith('tray-')) {
          return activeMenu.replace('tray-', '') as any;
      }
      return '';
  };

  return (
    <>
      <div className="fixed bottom-0 left-0 w-full h-[3.2rem] z-[5000] flex items-center shadow-[0_0_0.5rem_#171717] select-none">
        {/* Background Layer */}
        <span className="absolute inset-0 bg-[#2b2e33] z-[2]"></span>
        
        {/* Content Layer */}
        <div className="relative z-[3] w-full h-full flex items-center px-0">
            {/* Start Button */}
            <div 
                onClick={() => toggleMenu('start')}
                className="flex items-center justify-center mx-[0.4rem] cursor-pointer"
            >
            <Icon name="plasma" size="2.5rem" className="fill-white" />
            </div>

            {/* Pinned & Running Apps */}
            <div className="flex items-center h-full">
                <div className="flex h-full">
                    {pinnedApps.map(app => (
                    <AppIcon 
                        key={app.id} 
                        app={app} 
                        isActive={app.isOpen && !app.isMinimized}
                        onClick={() => handleAppClick(app.id, app.isOpen, app.isMinimized)}
                    />
                    ))}
                </div>
                
                {/* Separator - only implicit by flex/spacing in legacy, but we'll keep it clean */}
                
                <div className="flex h-full">
                    {runningUnpinnedApps.map(app => (
                    <AppIcon 
                        key={app.id} 
                        app={app} 
                        isActive={app.isOpen && !app.isMinimized}
                        onClick={() => handleAppClick(app.id, app.isOpen, app.isMinimized)}
                    />
                    ))}
                </div>
            </div>

            {/* Tray / Pendant */}
            <div className={clsx("ml-auto h-full flex relative", activeMenu === 'tray-arrow' && "before:content-[''] before:absolute before:w-[77%] before:h-[3px] before:bg-[#44bbff] before:top-0 before:left-[0.5rem]")}>
                <TrayIcon 
                    name="paste" 
                    isActive={activeMenu === 'tray-paste'} 
                    onClick={() => toggleMenu('tray-paste')} 
                />
                <TrayIcon 
                    name="keyboard" 
                    isActive={false} // Keyboard doesn't have a menu in legacy for now
                    onClick={() => {}} 
                />
                <TrayIcon 
                    name="audio-volume-muted" 
                    isActive={activeMenu === 'tray-volume'} 
                    onClick={() => toggleMenu('tray-volume')} 
                />
                <TrayIcon 
                    name="bluetooth" 
                    isActive={activeMenu === 'tray-bluetooth'} 
                    onClick={() => toggleMenu('tray-bluetooth')} 
                />
                <TrayIcon 
                    name="wifi" 
                    isActive={activeMenu === 'tray-wifi'} 
                    onClick={() => toggleMenu('tray-wifi')} 
                />
                <div 
                    onClick={() => toggleMenu('tray-arrow')}
                    className="h-full flex items-center mx-[0.1rem] px-[0.15rem] relative cursor-pointer trans"
                >
                    <Icon 
                        name="triangle" 
                        style={{ width: '1.1rem', height: '1.1rem' }} 
                        className={clsx("fill-white transition-transform", activeMenu === 'tray-arrow' ? "rotate-180" : "-rotate-90")} 
                    />
                </div>
                <div 
                    className="h-full flex items-center mx-[0.1rem] px-[0.15rem] relative cursor-pointer"
                    onClick={() => {
                        // Show desktop logic could go here
                    }}
                >
                    <Icon name="desktop" style={{ width: '2.2rem', height: '2.2rem' }} />
                </div>

                {/* Time */}
                <div 
                    onClick={() => toggleMenu('calendar')}
                    className="h-full flex flex-col justify-center text-white mx-[0.6rem] cursor-pointer select-none hover:bg-white/5 px-2"
                >
                    <time className="text-[1.2rem] leading-none text-center">{time.format('HH:mm')}</time>
                    <span className="text-[0.85rem] leading-none text-center mt-0.5">{time.format('DD MMM')}</span>
                </div>
            </div>
        </div>
      </div>

      {/* Menus */}
      <StartMenu isOpen={activeMenu === 'start'} onClose={() => setActiveMenu(null)} />
      <SystemTrayPopup view={getTrayView()} onClose={() => setActiveMenu(null)} />
      <CalendarWidget isOpen={activeMenu === 'calendar'} onClose={() => setActiveMenu(null)} />
    </>
  );
};

// Sub-components to match legacy styles exactly
const AppIcon = ({ app, isActive, onClick }: { app: any, isActive: boolean, onClick: () => void }) => (
    <div onClick={onClick} className="h-full flex items-center cursor-pointer px-1 hover:bg-white/10 group">
        <Icon 
            name={app.icon} 
            size="2rem" // Legacy didn't specify exact size in css for app icons but implied standard size
            className={clsx("transition-all duration-150", isActive ? "drop-shadow-[0_0_5px_rgba(255,255,255,0.5)]" : "group-hover:brightness-125 group-hover:saturate-200")}
        />
    </div>
);

const TrayIcon = ({ name, isActive, onClick }: { name: string, isActive: boolean, onClick: () => void }) => (
    <div 
        onClick={onClick}
        className={clsx(
            "h-full flex items-center mx-[0.1rem] px-[0.15rem] relative cursor-pointer",
            isActive && "before:content-[''] before:absolute before:w-[80%] before:h-[3px] before:bg-[#44bbff] before:top-0 before:left-[10%]"
        )}
    >
        <Icon name={name} style={{ width: '1.6rem', height: '1.6rem' }} className="fill-white" />
    </div>
);

// src/ref_views/taskbar/index.vue
<template>
  <section class="flex" id="taskbar">
    <i @click="toggleLeftMenu" class="icon-menu flex"
      ><svg-icon name="plasma"
    /></i>
    <div class="pinned flex">
      <app-icon
        v-for="app in pinnedApp"
        :class="'_item-' + app.name"
        :app="app"
      />
    </div>
    <div class="apps flex">
      <app-icon
        v-for="app in otherApp"
        :class="'_item-' + app.name"
        :app="app"
      />
    </div>

    <div class="pendant flex" :class="{ active: showRight === 'arrow' }">
      <i
        :class="{ active: showRight === 'paste' }"
        @click="toggleRightMenu('paste')"
      >
        <svg-icon name="paste" />
      </i>
      <i
        @click="
          keyboardType =
            keyboardType === 'keyboard' ? 'google-pinyin' : 'keyboard'
        "
      >
        <svg-icon :name="keyboardType" />
      </i>
      <i
        :class="{ active: showRight === 'volume' }"
        @click="toggleRightMenu('volume')"
      >
        <svg-icon name="audio-volume-muted" />
      </i>
      <i
        :class="{ active: showRight === 'bluetooth' }"
        @click="toggleRightMenu('bluetooth')"
      >
        <svg-icon name="bluetooth" />
      </i>
      <i
        :class="{ active: showRight === 'wifi' }"
        @click="toggleRightMenu('wifi')"
      >
        <svg-icon name="wifi" />
      </i>
      <i
        :class="{ toggled: showRight === 'arrow' }"
        @click="toggleRightMenu('arrow')"
        class="trans"
      >
        <svg-icon
          name="triangle"
          style="width: 1.1rem; height: 1.1rem; transform: rotate(-90deg)"
        />
      </i>
      <i @click="showDesktop">
        <svg-icon name="desktop" style="width: 2.2rem; height: 2.2rem" />
      </i>
      <div class="time flex" @click="toggleCalendar">
        <time>{{ time }}</time>
        <span>{{ date }}</span>
      </div>
    </div>

    <left-menu ref="leftmenu" :show="showLeft" @focusout="leftFocusout" />
    <right-menu :show="showRight" @focusout="rightFocusout" />
    <the-calendar
      ref="calendar"
      :show="showCalendar"
      @focusout="calendarFocusout"
    />
    <span class="bg"></span>
  </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import AppIcon from "./appIcon.vue";
import leftMenu from "./leftMenu.vue";
import rightMenu from "./rightMenu.vue";
import TheCalendar from "./calendar.vue";
import dayjs, { Dayjs } from "dayjs";
import { typeApp } from "../../utils/apps";
import mixin from "../../utils/mixin";

export default defineComponent({
  name: "index",
  components: { AppIcon, leftMenu, rightMenu, TheCalendar },
  data() {
    return {
      showLeft: false,
      showRight: "",
      showCalendar: false,
      oldShowRight: "",
      animation: false,

      arrowActive: false,
      keyboardType: "keyboard",
      timeStamp: dayjs(Date.now()) as Dayjs,
      showDesktopLis: [] as Array<string>,
    };
  },
  mixins: [mixin],
  computed: {
    pinnedApp(): Array<typeApp> {
      return this.apps
        .filter((app: typeApp) => app.taskbar != undefined)
        .sort((a: typeApp, b: typeApp) => a.taskbar - b.taskbar);
    },
    otherApp(): Array<typeApp> {
      return this.apps
        .filter(
          (app: typeApp) => app.order != undefined && app.status.value > 0,
        )
        .sort((a: typeApp, b: typeApp) => a.order.value - b.order.value);
    },
    time(): string {
      return this.timeStamp.format("HH:mm");
    },
    date(): string {
      return this.timeStamp.format("DD MMM");
    },
  },
  created() {
    setInterval(() => {
      this.timeStamp = dayjs(Date.now());
    }, 1000);
  },
  methods: {
    toggleLeftMenu() {
      if (this.animation) return;
      this.animation = false;
      !this.showLeft && (this.showLeft = !this.showLeft);
    },
    leftFocusout() {
      this.showLeft = false;
      this.animation = true;
      setTimeout(() => (this.animation = false), 200);
    },
    toggleRightMenu(type: string) {
      if (this.animation && this.oldShowRight === type) return;
      this.showRight = type;
    },
    rightFocusout() {
      this.oldShowRight = this.showRight;
      this.showRight = "";
      this.animation = true;
      setTimeout(() => (this.animation = false), 200);
    },
    showDesktop() {
      this.apps.map((app: typeApp) => {
        if (this.showDesktopLis.includes(app.name)) {
          app.status.value = 2;
          this.showDesktopLis.splice(
            this.showDesktopLis.indexOf(app.name) || 0,
            1,
          );
        } else if (app.status.value === 2) {
          app.status.value = 1;
          this.showDesktopLis.push(app.name);
        }
      });
    },
    toggleCalendar() {
      if (this.animation) return;
      this.showCalendar = !this.showCalendar;
      this.animation = false;
    },
    calendarFocusout() {
      this.showCalendar = false;
      this.animation = true;
      setTimeout(() => (this.animation = false), 200);
    },
  },
});
</script>

<style scoped lang="scss">
@use "src/assets/style/public" as *;

section {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  height: 3.2rem;
  box-shadow: 0 0 0.5rem #171717;
  z-index: $z-index-taskbar;
  > * {
    z-index: 3;
  }
  > span {
    position: absolute;
    background: #2b2e33;
    width: 100%;
    height: 100%;
    z-index: 2;
  }
  > .icon-menu:deep(> svg) {
    width: 2.5rem;
    height: 2.5rem;
    margin: 0 0.4rem;
    fill: white;
  }
  > .pinned {
    height: 100%;
  }
  > .apps {
    height: 100%;
  }
  .app {
    :deep(> svg) {
      transition: all 0.15s linear;
    }
    &:hover {
      :deep(> svg) {
        filter: saturate(4);
      }
    }
  }
  > .pendant {
    margin-left: auto;
    height: 100%;
    position: relative;
    &:before {
      content: "";
      position: absolute;
      width: 77%;
      height: 3px;
      background: #44bbff;
      top: 0;
      left: 0.5rem;
      opacity: 0;
      transition: opacity 0.1s linear;
    }
    &.active {
      &:before {
        opacity: 1;
      }
    }
    > i {
      height: 100%;
      display: flex;
      align-items: center;
      margin: 0 0.1rem;
      padding: 0 0.15rem;
      position: relative;
      :deep(> svg) {
        width: 1.6rem;
        height: 1.6rem;
        fill: white;
      }
      &:before {
        content: "";
        position: absolute;
        width: 80%;
        height: 3px;
        background: #44bbff;
        top: 0;
        left: 10%;
        opacity: 0;
        transition: opacity 0.1s linear;
      }
      &.active {
        &:before {
          opacity: 1;
        }
      }
      &.toggled {
        transform: rotate(180deg);
      }
    }
    > .time {
      height: 100%;
      flex-direction: column;
      color: white;
      margin: 0 0.6rem;
      justify-content: center;
      user-select: none;
      > time {
        font-size: 1.2rem;
      }
      > span {
        font-size: 0.85rem;
      }
    }
  }
}
</style>
