// src/ref_views/app/dolphin/index.vue
<template>
  <div class="dolphin flex">
    <div class="head flex">
      <div class="view flex">
        <span class="flex">
          <svg-icon
            @click="backDir"
            style="transform: rotate(-90deg)"
            name="arrow"
          />
          <svg-icon style="transform: rotate(90deg)" name="arrow" />
        </span>
        <svg-icon
          v-for="i in ['icons', 'details', 'tree']"
          :name="'view-list-' + i"
        />
      </div>
      <span class="flex"
        >/<svg-icon name="arrow" /><span @click="dirNow = []">home</span
        ><svg-icon name="arrow" /><span @click="dirNow = []">user</span>
        <template v-for="(dir, idx) in dirNow">
          <svg-icon name="arrow" /><span
            @click="dirNow = dirNow.slice(0, idx + 1)"
            >{{ dir }}</span
          >
        </template>
      </span>
    </div>
    <div class="body flex">
      <div class="menu flex">
        <span>Places</span>
        <div>
          <svg-icon name="folder-home" />
          <span>Home</span>
        </div>
        <div>
          <svg-icon name="folder-desktop" />
          <span>Desktop</span>
        </div>
        <div>
          <svg-icon name="folder-documents" />
          <span>Documents</span>
        </div>
        <div>
          <svg-icon name="folder-download" />
          <span>Downloads</span>
        </div>
        <div>
          <svg-icon name="folder-music" />
          <span>Music</span>
        </div>
        <div>
          <svg-icon name="folder-image" />
          <span>Pictures</span>
        </div>
        <div>
          <svg-icon name="folder-video" />
          <span>Videos</span>
        </div>
        <div>
          <svg-icon name="folder-trash" />
          <span>Trash</span>
        </div>
        <span>Remote</span>
        <div>
          <svg-icon name="folder-network" />
          <span>Network</span>
        </div>
      </div>
      <div class="detail flex">
        <div
          tabindex="1"
          class="flex"
          v-for="i in filesNow"
          @dblclick="processFile(i)"
        >
          <svg-icon :name="calcMimeIcon(i.mime)" />
          <span>{{ i.name }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import mixin from "../../../utils/mixin";
import { defineComponent } from "vue";
import { openApp } from "../../../utils/utils";
import { typeFile, dolphinFiles } from "../../../../filesystem";

export default defineComponent({
  name: "index",
  data() {
    return {
      dirNow: [],
      dolphinFiles,
    };
  },
  mixins: [mixin],
  computed: {
    filesNow(): Array<typeFile> {
      let idx = 0;
      let parent = this.dolphinFiles;
      while (idx < this.dirNow.length) {
        parent = parent.find((v) => v.name === this.dirNow[idx]).sub;
        idx++;
      }
      return parent;
    },
  },
  methods: {
    backDir() {
      if (this.dirNow.length > 0) {
        this.dirNow.pop();
      }
    },
    calcMimeIcon(mime: string) {
      const mimes = mime.split("/");
      if (mimes[0] === "image") {
        return "mime-image";
      }
      return "mime-" + mimes.join("-");
    },
    processFile(f: typeFile) {
      if (f.isDir) {
        this.dirNow.push(f.name);
        return;
      }
      const filepath = this.dirNow.concat(f.name).join("/");
      const mimes = f.mime.split("/");
      if (mimes[0] === "image") {
        openApp.call(this, "image viewer").params.filepath.value = filepath;
      }
      switch (f.mime) {
        case "text/markdown":
          openApp.call(this, "gedit").params.filepath.value = filepath;
          break;
        case "audio/mpeg":
          openApp.call(this, "music").params.filepath.value = filepath;
          break;
      }
    },
  },
});
</script>

<style scoped lang="scss">
.dolphin {
  color: white;
  width: 100%;
  height: 100%;
  flex-direction: column;
  > .head {
    background: #31363b;
    width: 100%;
    > .view {
      width: 30%;
      > span {
        justify-content: space-around;
        border-right: 1px solid #6d6d6d;
        padding: 0.2rem 0;
        width: 4.5rem;
        :deep(> svg) {
          width: 1.2rem;
          height: 1.2rem;
          fill: white;
        }
      }
      :deep(> svg) {
        width: 1.5rem;
        height: 1.5rem;
        margin-left: 0.4rem;
        &:first-of-type {
          background: rgba(255, 255, 255, 0.15);
          border-radius: 0.2rem;
        }
      }
      :deep(svg) {
        padding: 0.25rem;
        border: 1px solid transparent;
        border-radius: 0.15rem;
        &:hover {
          border-color: #44bbff;
        }
      }
    }
    > span {
      width: 70%;
      font-size: 0.8rem;
      :deep(> svg) {
        width: 0.7rem;
        height: 0.7rem;
        margin: 0 0.7rem;
        fill: white;
        transform: rotate(95deg);
      }
    }
  }
  > .body {
    width: 100%;
    flex-grow: 1;
    > .menu {
      height: 100%;
      width: 30%;
      background: #31363b;
      flex-direction: column;
      > span {
        width: 100%;
        font-size: 0.95rem;
        color: #979797;
        margin: 0.5rem 0 0.5rem 0.4rem;
      }
      > div {
        margin-bottom: 0.3rem;
        display: flex;
        align-items: center;
        transition: all 0.2s linear;
        width: 100%;
        padding: 0.15rem 0;
        &:hover {
          background: #44bbff33;
        }
        :deep(> svg) {
          width: 1rem;
          height: 1rem;
          margin: 0 0.4rem;
        }
        > span {
          font-size: 0.8rem;
        }
      }
    }
    > .detail {
      height: 100%;
      width: 70%;
      align-items: flex-start;
      > div {
        width: 6.5rem;
        height: 6.5rem;
        justify-content: center;
        flex-direction: column;
        border: 1px solid transparent;
        margin: 0.4rem;
        user-select: none;
        border-radius: 0.15rem;
        &:hover {
          background: rgba(255, 255, 255, 0.05);
          border-color: #658ca1;
        }
        &:focus {
          background: #44bbff33;
          border-color: #44bbff;
        }
        :deep(> svg) {
          width: 4rem;
          height: 4rem;
        }
        > span {
          font-size: 0.8rem;
          word-break: break-all;
          text-align: center;
          height: 2rem;
        }
      }
    }
  }
}
</style>

// src/components/apps/Dolphin.tsx
import { useState } from 'react';
import { Icon } from '@/components/Icon';
import clsx from 'clsx';
import { useDesktopStore } from '@/store/useDesktopStore';
import { dolphinFiles, typeFile } from '@/utils/filesystem';

export const Dolphin = () => {
  const [path, setPath] = useState<string[]>([]); // Empty = Home
  const { openApp, setAppParams } = useDesktopStore();

  // Helper to get files at current path
  const getFilesAtCurrentPath = (): typeFile[] => {
      let current = dolphinFiles;
      for (const p of path) {
          const found = current.find(f => f.name === p && f.isDir);
          if (found && found.sub) {
              current = found.sub;
          } else {
              return [];
          }
      }
      return current;
  };

  const files = getFilesAtCurrentPath();

  const handleDoubleClick = (file: typeFile) => {
      if (file.isDir) {
          setPath([...path, file.name]);
      } else {
          // Open file logic
          const filepath = [...path, file.name].join('/');
          const mime = file.mime;
          
          if (mime.startsWith('image/')) {
              setAppParams('image-viewer', { filepath });
              openApp('image-viewer');
          } else if (mime.startsWith('audio/')) {
              setAppParams('music', { filepath });
              openApp('music');
          } else if (mime === 'text/markdown') {
              setAppParams('gedit', { filepath });
              openApp('gedit');
          }
      }
  };

  const navigateUp = () => {
      if (path.length > 0) {
          setPath(path.slice(0, -1));
      }
  };

  return (
    <div className="w-full h-full flex flex-col text-white bg-[#2b2e33]">
       {/* Toolbar */}
       <div className="h-10 bg-[#31363b] border-b border-gray-600 flex items-center px-2">
          <div className="flex items-center gap-1 mr-4 text-gray-400">
             <button onClick={navigateUp} className="p-1 hover:text-white"><Icon name="arrow" size={14} className="rotate-90" /></button>
             <button className="p-1 hover:text-white"><Icon name="arrow" size={14} className="-rotate-90" /></button>
          </div>
          
          <div className="flex items-center text-sm bg-[#212121]/50 px-2 py-1 rounded flex-1">
             <Icon name="folder-home" size={14} className="mr-2" />
             <span className="text-gray-400">/ home / yunyuyuan / </span>
             <span className="ml-1">{path.join(' / ')}</span>
          </div>
       </div>

       <div className="flex-1 flex overflow-hidden">
          {/* Sidebar */}
          <div className="w-40 bg-[#31363b] flex flex-col p-2 gap-1 text-sm border-r border-gray-600">
             <span className="text-xs text-gray-500 font-bold px-2 mt-2 uppercase">Places</span>
             <SidebarItem icon="folder-home" label="Home" active={path.length === 0} onClick={() => setPath([])} />
             <SidebarItem icon="folder-desktop" label="Desktop" />
             <SidebarItem icon="folder-documents" label="Documents" />
             <SidebarItem icon="folder-download" label="Downloads" />
             <SidebarItem icon="folder-trash" label="Trash" />
          </div>

          {/* Content */}
          <div className="flex-1 p-2 flex flex-wrap content-start gap-2 bg-[#1e1e1e]">
             {files.map((file, i) => (
                 <div 
                   key={i}
                   onDoubleClick={() => handleDoubleClick(file)}
                   className="w-24 h-24 flex flex-col items-center justify-center rounded hover:bg-white/10 cursor-pointer border border-transparent hover:border-gray-600"
                 >
                    <Icon name={getIconForFile(file)} size={48} className="mb-2" />
                    <span className="text-xs text-center px-1 truncate w-full text-white">{file.name}</span>
                 </div>
             ))}
          </div>
       </div>
    </div>
  );
};

const getIconForFile = (file: typeFile) => {
    if (file.isDir) {
        // Simple mapping for known folders
        if (['images', 'musics'].includes(file.name)) return `folder-${file.name === 'images' ? 'image' : 'music'}`;
        return 'folder-home'; // Default folder icon
    }
    const mime = file.mime;
    if (mime.startsWith('image/')) return 'mime-image';
    if (mime.startsWith('audio/')) return 'mime-audio-mpeg';
    if (mime === 'text/markdown') return 'mime-text-markdown';
    return 'file'; // Default file icon (needs svg)
};

const SidebarItem = ({ icon, label, active, onClick }: any) => (
    <div 
      onClick={onClick}
      className={clsx(
        "flex items-center px-2 py-1.5 rounded cursor-pointer transition-colors",
        active ? "bg-[#44bbff]/20 text-[#44bbff]" : "hover:bg-white/5 text-gray-300"
      )}
    >
       <Icon name={icon} size={16} className="mr-3" />
       <span>{label}</span>
    </div>
);
