// src/ref_views/app/music/index.vue
<template>
  <div class="music">
    <div class="list">
      <div
        v-for="(filepath, idx) in audioFiles"
        :class="{ active: activeIdx === idx }"
        @click="activeIdx = idx"
        class="trans"
      >
        <span class="name">{{ filepath.split("/").pop() }}</span>
      </div>
    </div>
    <div class="player flex">
      <div class="control flex">
        <span @click="turn(-1)">
          <svg-icon style="transform: rotate(180deg)" name="triangle" />
        </span>
        <div @click="pause">
          <svg-icon :name="calcPlaySvg" />
        </div>
        <span @click="turn(1)">
          <svg-icon name="triangle" />
        </span>
      </div>
      <div class="progress flex">
        <Slider
          v-model="fakePlayDuration"
          @change="changeCurrentTime"
          :tooltips="false"
          :min="0"
          :max="duration"
          :disabled="loading"
          @mousedown.capture="waitSlide = true"
          height="100%"
        />
        <time>{{ playTime }}</time>
      </div>
      <div class="right flex" tabindex="1">
        <svg-icon
          :style="{ fill: volumeActive ? 'rgb(0 208 255)' : 'white' }"
          @click="volumeActive = !volumeActive"
          name="audio-volume-high"
        />
        <div class="volume flex" :class="{ active: volumeActive }">
          <Slider
            v-model="volume"
            :tooltips="false"
            :min="0"
            :max="1"
            :step="0.01"
            orientation="vertical"
            direction="rtl"
            height="70%"
          />
        </div>
      </div>
      <audio @ended="turn(1)"></audio>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, watchEffect } from "vue";
import { findMimeFiles } from "../../../utils/utils";
import Slider from "@vueform/slider";
import "@vueform/slider/themes/default.css";
import dayjs from "dayjs";
import duration from "dayjs/plugin/duration";
dayjs.extend(duration);

export default defineComponent({
  name: "index",
  components: {
    Slider,
  },
  data() {
    return {
      activeIdx: -1,
      canAutoPlay: false,
      waitSlide: false,

      paused: true,
      loading: false,
      duration: 60,
      playDuration: 0,
      fakePlayDuration: 0,
      volume: 0.8,
      volumeActive: false,
    };
  },
  inject: ["apps"],
  computed: {
    audioFiles() {
      return findMimeFiles(/^audio\//);
    },
    activeFile() {
      if (this.activeIdx >= 0) {
        return "/dolphin-files/" + this.audioFiles[this.activeIdx];
      }
    },
    playTime() {
      return dayjs.duration(this.playDuration * 1000).format("mm:ss");
    },
    calcPlaySvg() {
      if (this.loading) {
        return "loading";
      }
      if (this.paused) {
        return "media-play";
      }
      return "media-pause";
    },
    audio(): HTMLAudioElement {
      return this.$el.querySelector("audio");
    },
  },
  watch: {
    activeFile(val) {
      this.canAutoPlay = true;
      try {
        this.audio.pause();
      } catch (e) {}

      this.paused = true;
      this.loading = true;
      this.playDuration = 0;
      this.fakePlayDuration = 0;

      const request = new XMLHttpRequest();
      request.open("GET", val, true);
      request.responseType = "blob";
      request.onload = () => {
        if (request.status == 200) {
          this.audio.src = URL.createObjectURL(request.response);
          this.audio.load();
          this.audio.play();
        }
      };
      request.send();
    },
    playDuration() {
      if (this.audio.paused) {
        this.paused = false;
        this.audio.play();
      }
    },
    volume() {
      this.audio.volume = this.volume;
    },
  },
  created() {
    watchEffect(() => {
      const filepath = this.apps.find((app) => app.name === "music").params
        .filepath.value;
      if (filepath) {
        this.activeIdx = this.audioFiles.indexOf(filepath);
      }
    });
  },
  mounted() {
    this.audio.volume = this.volume;
    this.audio.addEventListener("loadeddata", () => {
      this.duration = this.audio.duration;
      if (this.canAutoPlay) {
        this.loading = false;
        this.paused = false;
        this.audio.play();
      }
    });
    this.audio.addEventListener("timeupdate", () => {
      this.playDuration = Math.floor(this.audio.currentTime);
      if (!this.waitSlide) {
        // change slider
        this.fakePlayDuration = this.playDuration;
      }
    });
  },
  methods: {
    turn(to: number) {
      if (this.activeIdx === 0 && to === -1) {
        this.activeIdx = this.audioFiles.length - 1;
        return;
      }
      this.activeIdx = (this.activeIdx + to) % this.audioFiles.length;
    },
    pause() {
      if (this.loading) return;
      this.paused = !this.paused;
      if (this.paused) {
        this.audio.pause();
      } else {
        this.audio.play();
      }
    },
    changeCurrentTime() {
      this.playDuration = this.fakePlayDuration;
      this.audio.currentTime = this.playDuration;
      this.waitSlide = false;
    },
  },
  beforeUnmount() {
    if (!this.audio.paused) {
      this.audio.pause();
    }
  },
});
</script>

<style scoped lang="scss">
.music {
  width: 100%;
  height: 100%;
  overflow: hidden !important;
  position: relative;
  > .list {
    width: 100%;
    height: calc(100% - 4rem);
    overflow: auto;
    background: #ffffff;
    > div {
      padding: 0.8rem;
      border-left: 5px solid transparent;
      border-bottom: 1px solid rgba(139, 110, 110, 0.3);
      cursor: pointer;
      &:hover {
        background: #44bbff33;
      }
      &.active {
        border-left-color: #ff6300;
      }
    }
  }
  > .player {
    position: absolute;
    left: 0;
    width: 100%;
    height: 4rem;
    background: #2a2a2a;
    color: white;
    box-shadow: 0 0 1rem rgb(44, 122, 146);
    user-select: none;
    > * {
      height: 100%;
    }
    > .control {
      width: 10rem;
      flex-shrink: 0;
      justify-content: space-evenly;
      margin: 0 0.5rem;
      > * {
        border-radius: 50%;
        background: #00ffcf;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
        cursor: pointer;
        transition: all 0.15s linear;
        &:hover {
          background: #1eecff;
        }
        :deep(> svg) {
          width: 100%;
          height: 100%;
          fill: black;
        }
      }
      > span {
        padding: 0.4rem;
        width: 1.1rem;
        height: 1.1rem;
      }
      > div {
        padding: 0.7rem;
        width: 1.5rem;
        height: 1.5rem;
      }
    }
    > .progress {
      flex-grow: 1;
      > div {
        flex-grow: 1;
        :deep(.slider-origin) {
          transition: none !important;
        }
      }
      > time {
        font-size: 0.8rem;
        word-break: keep-all;
        margin-left: 0.8rem;
      }
    }
    > .right {
      width: 6rem;
      flex-shrink: 0;
      position: relative;
      flex-direction: column;
      justify-content: center;
      :deep(> svg) {
        width: 2rem;
        height: 2rem;
      }
      > .volume {
        position: absolute;
        top: 0;
        z-index: 1;
        height: 0;
        overflow: hidden;
        justify-content: center;
        width: 2rem;
        transform: translateY(calc(-100% - 0.4rem));
        &.active {
          height: 6rem;
          border-radius: 0.2rem;
          box-shadow: 0 0 1rem rgba(0, 0, 0, 0.4);
          background: #1f1f1f;
        }
      }
    }
  }
}
</style>

// src/components/apps/Music.tsx
import { useDesktopStore } from '@/store/useDesktopStore';
import { findMimeFiles } from '@/utils/utils';
import { useEffect, useRef, useState } from 'react';
import { Icon } from '@/components/Icon';
import clsx from 'clsx';
import dayjs from 'dayjs';
import duration from 'dayjs/plugin/duration';

dayjs.extend(duration);

export const Music = () => {
  const { apps } = useDesktopStore();
  const app = apps.find(a => a.id === 'music');
  
  const [activeIdx, setActiveIdx] = useState(-1);
  const [paused, setPaused] = useState(true);
  const [currentTime, setCurrentTime] = useState(0);
  const [durationTime, setDurationTime] = useState(0);
  const [volume, setVolume] = useState(0.8);
  const audioRef = useRef<HTMLAudioElement>(null);

  const audioFiles = findMimeFiles(/^audio\//);

  // Handle opening from file parameter
  useEffect(() => {
    const filepath = app?.params?.filepath;
    if (filepath) {
      const idx = audioFiles.indexOf(filepath);
      if (idx >= 0) {
        setActiveIdx(idx);
      }
    }
  }, [app?.params?.filepath]);

  // Auto-play when track changes
  useEffect(() => {
      if (activeIdx >= 0 && audioRef.current) {
          audioRef.current.src = `/dolphin-files/${audioFiles[activeIdx]}`;
          audioRef.current.load();
          audioRef.current.play().catch(e => console.log("Autoplay blocked", e));
          setPaused(false);
      }
  }, [activeIdx]);

  useEffect(() => {
      if (audioRef.current) {
          audioRef.current.volume = volume;
      }
  }, [volume]);

  const handleTimeUpdate = () => {
      if (audioRef.current) {
          setCurrentTime(audioRef.current.currentTime);
      }
  };

  const handleLoadedData = () => {
      if (audioRef.current) {
          setDurationTime(audioRef.current.duration);
      }
  };

  const togglePlay = () => {
      if (audioRef.current) {
          if (paused) {
              audioRef.current.play();
          } else {
              audioRef.current.pause();
          }
          setPaused(!paused);
      }
  };

  const playNext = () => {
      if (audioFiles.length === 0) return;
      setActiveIdx((prev) => (prev + 1) % audioFiles.length);
  };

  const playPrev = () => {
      if (audioFiles.length === 0) return;
      setActiveIdx((prev) => (prev - 1 + audioFiles.length) % audioFiles.length);
  };

  return (
    <div className="w-full h-full bg-white flex flex-col overflow-hidden">
       {/* Playlist */}
       <div className="flex-1 overflow-y-auto bg-white">
          {audioFiles.map((file, idx) => (
              <div 
                key={file}
                onClick={() => setActiveIdx(idx)}
                className={clsx(
                    "p-3 border-b border-gray-200 cursor-pointer hover:bg-[#44bbff]/20 transition-colors border-l-[5px]",
                    activeIdx === idx ? "border-l-[#ff6300] bg-[#44bbff]/20" : "border-l-transparent"
                )}
              >
                 <span className="text-sm text-gray-800">{file.split('/').pop()}</span>
              </div>
          ))}
       </div>

       {/* Player Controls */}
       <div className="h-16 bg-[#2a2a2a] text-white flex items-center px-4 shadow-[0_0_1rem_rgb(44,122,146)] z-10">
          <div className="flex items-center gap-4 mr-4">
             <button onClick={playPrev} className="w-8 h-8 rounded-full bg-[#00ffcf] hover:bg-[#1eecff] flex items-center justify-center text-black transition-colors">
                <Icon name="triangle" size={14} className="rotate-180" />
             </button>
             <button onClick={togglePlay} className="w-10 h-10 rounded-full bg-[#00ffcf] hover:bg-[#1eecff] flex items-center justify-center text-black transition-colors">
                <Icon name={paused ? "media-play" : "media-pause"} size={20} />
             </button>
             <button onClick={playNext} className="w-8 h-8 rounded-full bg-[#00ffcf] hover:bg-[#1eecff] flex items-center justify-center text-black transition-colors">
                <Icon name="triangle" size={14} />
             </button>
          </div>

          <div className="flex-1 flex items-center gap-4">
             <input 
               type="range" 
               min="0" 
               max={durationTime || 100} 
               value={currentTime} 
               onChange={(e) => {
                   const val = Number(e.target.value);
                   setCurrentTime(val);
                   if (audioRef.current) audioRef.current.currentTime = val;
               }}
               className="flex-1 h-1 bg-gray-600 rounded-lg appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:bg-[#00ffcf] [&::-webkit-slider-thumb]:rounded-full"
             />
             <span className="text-xs font-mono w-12 text-right">
                 {dayjs.duration(currentTime * 1000).format('mm:ss')}
             </span>
          </div>

          <div className="ml-4 flex items-center gap-2 group relative">
             <Icon name="audio-volume-high" size={24} className="cursor-pointer text-white hover:text-[#00d0ff]" />
             <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 w-8 h-24 bg-[#1f1f1f] rounded shadow-lg hidden group-hover:flex items-center justify-center pb-2">
                 <input 
                   type="range" 
                   min="0" 
                   max="1" 
                   step="0.01"
                   value={volume} 
                   onChange={(e) => setVolume(Number(e.target.value))}
                   className="h-20 -rotate-90 appearance-none bg-gray-600 rounded w-1 [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-3 [&::-webkit-slider-thumb]:h-3 [&::-webkit-slider-thumb]:bg-[#00ffcf] [&::-webkit-slider-thumb]:rounded-full"
                 />
             </div>
          </div>
       </div>
       
       <audio 
         ref={audioRef} 
         onTimeUpdate={handleTimeUpdate} 
         onLoadedData={handleLoadedData}
         onEnded={playNext}
       />
    </div>
  );
};
