// src/ref_views/app/settings/index.vue
<template>
  <div class="settings flex">
    <div class="head flex">
      <div class="flex">
        <input class="common" placeholder="Search..." />
      </div>
      <span>{{ activeTab }}</span>
    </div>
    <div class="body flex">
      <div class="menu">
        <div
          @click="activeTab = 'Kernel'"
          :class="{ active: activeTab === 'Kernel' }"
        >
          <svg-icon name="settings" /><span>Kernel</span>
        </div>
        <div
          @click="activeTab = 'Keyboard Settings'"
          :class="{ active: activeTab === 'Keyboard Settings' }"
        >
          <svg-icon name="settings-keyboard" /><span>Keyboard Settings</span>
        </div>
        <div
          @click="activeTab = 'Locale'"
          :class="{ active: activeTab === 'Locale' }"
        >
          <svg-icon name="locale" /><span>Locale</span>
        </div>
        <div
          @click="activeTab = 'Time and Date'"
          :class="{ active: activeTab === 'Time and Date' }"
        >
          <svg-icon name="settings-time" /><span>Time and Date</span>
        </div>
        <div
          @click="activeTab = 'User Accounts'"
          :class="{ active: activeTab === 'User Accounts' }"
        >
          <svg-icon name="settings-user" /><span>User Accounts</span>
        </div>
      </div>
      <div class="detail">
        <div v-if="activeTab === 'Kernel'" class="kernel flex">
          <div class="flex">
            <svg-icon name="manjaro" />
            <span class="flex">
              <b>Manjaro Linux</b>
              <a href="https://manjaro.org" target="_blank"
                >https://manjaro.org/</a
              >
            </span>
          </div>
          <span>
            <a>KDE Plasma Version:</a>
            <span>5.21.4</span>
          </span>
          <span>
            <a>KDE Frameworks Version:</a>
            <span>5.81.0</span>
          </span>
          <span>
            <a>Qt Version:</a>
            <span>5.15.2</span>
          </span>
          <span>
            <a>Kernel Version:</a>
            <span>5.10.34-1-MANJARO</span>
          </span>
          <span>
            <a>OS Type:</a>
            <span>64-bit</span>
          </span>
          <span>
            <a>Graphics Platform:</a>
            <span>X11</span>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
export default {
  name: "index",
  data() {
    return {
      activeTab: "Kernel",
    };
  },
};
</script>

<style scoped lang="scss">
.settings {
  width: 100%;
  height: 100%;
  color: white;
  flex-direction: column;
  > .head {
    background: #31363b;
    border-bottom: 1px solid gray;
    width: 100%;
    > div {
      padding: 0.5rem 0;
      width: 30%;
      > input {
        width: 80%;
      }
      border-right: 1px solid gray;
    }
    > span {
      width: calc(70% - 1rem);
      padding-left: 1rem;
      font-size: 1.25rem;
    }
  }
  > .body {
    width: 100%;
    flex-grow: 1;
    > .menu {
      width: 30%;
      height: 100%;
      border-right: 1px solid gray;
      > div {
        padding: 0.4rem 0;
        border-bottom: 1px solid rgba(94, 77, 77, 0.3);
        display: flex;
        align-items: center;
        &.active {
          background: #44bbff88;
        }
        &:not(.active):hover {
          background: #7dcfff33;
        }
        :deep(> svg) {
          margin: 0 0.4rem;
          width: 1.5rem;
          height: 1.5rem;
        }

        > span {
          font-size: 0.8rem;
        }
      }
    }
    > .detail {
      width: 70%;
      height: 100%;
      > .kernel {
        width: 100%;
        flex-direction: column;
        > div {
          justify-content: center;
          margin: 2rem 0;
          :deep(> svg) {
            width: 7rem;
            height: 7rem;
          }
          > span {
            margin-left: 1rem;
            flex-direction: column;
            > b {
              font-size: 1.5rem;
            }
            > a {
              margin-top: 0.5rem;
              color: #2980b9;
              font-size: 0.9rem;
            }
          }
        }
        > span {
          width: 20rem;
          font-size: 0.84rem;
          margin-bottom: 0.6rem;
          display: flex;
          align-items: center;
          > a {
            width: 10rem;
            text-align: right;
            white-space: nowrap;
          }
          > span {
            margin-left: 0.5rem;
          }
        }
      }
    }
  }
}
</style>

// src/components/apps/Settings.tsx
import { useState } from 'react';
import { Icon } from '@/components/Icon';
import clsx from 'clsx';

const SettingsTabs = ['Kernel', 'Keyboard Settings', 'Locale', 'Time and Date', 'User Accounts'];

export const Settings = () => {
  const [activeTab, setActiveTab] = useState('Kernel');

  return (
    <div className="w-full h-full flex flex-col text-white bg-[#2b2e33]">
       {/* Header */}
       <div className="h-10 bg-[#31363b] border-b border-gray-600 flex items-center">
          <div className="w-[30%] h-full border-r border-gray-600 flex items-center px-2">
             <input className="w-full bg-[#212121] border border-gray-500 rounded px-2 py-0.5 text-sm outline-none focus:border-[#44bbff]" placeholder="Search..." />
          </div>
          <div className="w-[70%] h-full flex items-center px-4 text-lg font-light">
             {activeTab}
          </div>
       </div>

       {/* Body */}
       <div className="flex-1 flex overflow-hidden">
          {/* Sidebar */}
          <div className="w-[30%] h-full border-r border-gray-600 bg-[#2b2e33] flex flex-col">
             {SettingsTabs.map(tab => (
               <button
                 key={tab}
                 onClick={() => setActiveTab(tab)}
                 className={clsx(
                   "flex items-center px-2 py-2 hover:bg-[#7dcfff]/20 transition-colors text-left",
                   activeTab === tab && "bg-[#44bbff]/50"
                 )}
               >
                  <Icon name={getIconForTab(tab)} size={20} className="mr-3" />
                  <span className="text-sm">{tab}</span>
               </button>
             ))}
          </div>

          {/* Content */}
          <div className="w-[70%] h-full p-8 overflow-y-auto bg-[#2b2e33]">
             {activeTab === 'Kernel' && (
               <div className="flex flex-col items-center gap-6">
                  <div className="flex items-center gap-4 mb-4">
                     <Icon name="manjaro" size={96} />
                     <div className="flex flex-col">
                        <span className="text-2xl font-bold">Manjaro Linux</span>
                        <a href="https://manjaro.org" target="_blank" className="text-[#2980b9] hover:underline">https://manjaro.org/</a>
                     </div>
                  </div>

                  <div className="w-full max-w-md space-y-2 text-sm">
                     <InfoRow label="KDE Plasma Version:" value="5.21.4" />
                     <InfoRow label="KDE Frameworks Version:" value="5.81.0" />
                     <InfoRow label="Qt Version:" value="5.15.2" />
                     <InfoRow label="Kernel Version:" value="5.10.34-1-MANJARO" />
                     <InfoRow label="OS Type:" value="64-bit" />
                     <InfoRow label="Graphics Platform:" value="X11" />
                  </div>
               </div>
             )}
             {activeTab !== 'Kernel' && (
                 <div className="flex flex-col items-center justify-center h-full text-gray-500">
                     <Icon name="settings" size={64} className="opacity-20 mb-4" />
                     <p>Not implemented yet.</p>
                 </div>
             )}
          </div>
       </div>
    </div>
  );
};

const InfoRow = ({ label, value }: { label: string, value: string }) => (
    <div className="flex">
        <span className="w-1/2 text-right text-gray-400 pr-4">{label}</span>
        <span className="w-1/2 text-left font-medium">{value}</span>
    </div>
);

const getIconForTab = (tab: string) => {
    switch (tab) {
        case 'Kernel': return 'settings';
        case 'Keyboard Settings': return 'settings-keyboard';
        case 'Locale': return 'locale';
        case 'Time and Date': return 'settings-time';
        case 'User Accounts': return 'settings-user';
        default: return 'settings';
    }
};
