// src/ref_views/app/terminal/index.vue
<template>
  <div class="terminal code-font" @click.self="focusInput">
    <p>> Enjoy the fake terminal 😆. And there have an Easter Egg.</p>
    <div v-for="item in cmds">
      <b class="header" v-if="item[0] === 'cmd'"
        >[user@manjaro <span>{{ item[2] }}</span
        >]$</b
      >
      <span class="content" :class="item[0]" v-html="item[1]"></span>
    </div>
    <div>
      <b class="header"
        >[user@manjaro <span>{{ dirStr }}</span
        >]$</b
      >
      <input
        ref="input"
        class="code-font"
        v-model.trim="input"
        @keydown.up.prevent="upCmd"
        @keydown.down.prevent="downCmd"
        @keydown.enter="processCmd"
        @keydown.tab.prevent="autoComplete"
      />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, inject, Ref } from "vue";
import { escapeHtml, openApp } from "../../../utils/utils";
import mixin from "../../../utils/mixin";
import { typeFile, dolphinFiles } from "../../../../filesystem";

const helps = [
  ["ls", "list files or folders"],
  ["cd <dir>", "change current directory to dir"],
  ["clear", "clear screen"],
  ["pwd", "print work directory"],
  ["xdg-open <file>", "open a file"],
  ["poweroff", "close manjaro"],
  ["reboot", "reboot manjaro"],
];

export default defineComponent({
  name: "index",
  data() {
    return {
      dir: [],
      input: "",
      cmds: [],
      history: [],
      hisIdx: -1,

      dolphinFiles,
    };
  },
  mixins: [mixin],
  computed: {
    cmdLis(): Array<string> {
      return this.input.split(/\s+/);
    },
    filesNow(): Array<typeFile> {
      let idx = 0;
      let parent = this.dolphinFiles;
      while (idx < this.dir.length) {
        parent = parent.find((v) => v.name === this.dir[idx]).sub;
        idx++;
      }
      return parent;
    },
    dirsNow(): Array<typeFile> {
      return this.filesNow.filter((v) => v.isDir);
    },
    notDirsNow(): Array<typeFile> {
      return this.filesNow.filter((v) => !v.isDir);
    },
    dirStr(): string {
      return this.dir.length ? this.dir.join("/") : "~";
    },
  },
  watch: {
    cmds: {
      deep: true,
      handler() {
        if (!this.$el) return;
        this.$nextTick(() => {
          this.$el.scrollTop = this.$el.scrollHeight + 100;
        });
      },
    },
  },
  setup() {
    return {
      power: inject("power") as Ref,
    };
  },
  mounted() {
    this.$el.querySelector("input").focus();
  },
  methods: {
    focusInput() {
      this.$refs.input.focus();
    },
    pushCmd(cmd: string) {
      this.cmds.push(["cmd", cmd, this.dirStr]);
    },
    processCmd() {
      if (this.input !== "") {
        this.history.push(this.input);
      }
      this.hisIdx = -1;
      switch (this.cmdLis[0]) {
        case "":
          this.pushCmd("");
          break;
        case "help":
          this.pushCmd(this.input);
          this.cmds.push([
            "out",
            helps
              .map((v) => `<p>${escapeHtml(v[0])}</p>${escapeHtml(v[1])}\n`)
              .join(""),
          ]);
          break;
        case "ls":
          this.pushCmd(this.input);
          this.cmds.push([
            "out",
            this.filesNow
              .map((v) => (v.isDir ? `<span>${v.name}</span>` : v.name))
              .join("\n"),
          ]);
          break;
        case "poweroff":
          this.power = "shutdown";
          break;
        case "reboot":
          this.power = "reboot";
          break;
        case "cd":
          this.pushCmd(this.input);
          if (this.cmdLis.length > 2) {
            this.cmds.push(["out", 'command "cd" only take one argument']);
          } else {
            const dir = this.cmdLis[1];
            // Todo: support '/'
            if (dir && dir.includes("/")) {
              this.cmds.push(["out", "No support for multiple dir currently"]);
              break;
            }
            switch (dir) {
              case undefined:
              case "~":
                this.dir = [];
                break;
              case "..":
                if (this.dir.length > 0) this.dir.pop();
                break;
              case ".":
                break;
              default:
                if (this.dirsNow.find((v) => v.name === dir)) {
                  this.dir.push(dir);
                } else {
                  this.cmds.push(["out", "Unknown folder: " + dir]);
                }
                break;
            }
          }
          break;
        case "clear":
          this.cmds = [];
          break;
        case "pwd":
          this.pushCmd(this.input);
          this.cmds.push(["out", this.dirStr]);
          break;
        case "I":
          this.pushCmd(this.input);
          if (
            this.cmdLis.length === 3 &&
            ["like", "love"].includes(this.cmdLis[1]) &&
            ["you", "u"].includes(this.cmdLis[2])
          ) {
            this.pushCmd(this.input);
            this.cmds.push([
              "out",
              `<a style="color: #ff7474">I ${this.cmdLis[1]} ${this.cmdLis[2]} too.😽</a>`,
            ]);
          } else {
            this.cmds.push(["out", 'Unknown command: "' + this.input + '"']);
          }
          break;
        case "xdg-open":
          this.pushCmd(this.input);
          if (this.cmdLis.length > 2) {
            this.cmds.push([
              "out",
              'command "xdg-open" only take one argument',
            ]);
          } else {
            if (this.cmdLis[1]) {
              const file = this.filesNow.find(
                (v) => !v.isDir && v.name === this.cmdLis[1],
              );
              if (file) {
                const mime1 = file.mime.split("/")[0];
                switch (file.mime) {
                  case "text/markdown":
                    openApp.call(this, "gedit").params.filepath.value = this.dir
                      .concat([file.name])
                      .join("/");
                    break;
                  case "audio/mpeg":
                    openApp.call(this, "music").params.filepath.value = this.dir
                      .concat([file.name])
                      .join("/");
                    break;
                  default:
                    if (mime1 === "image") {
                      openApp.call(this, "image viewer").params.filepath.value =
                        this.dir.concat([file.name]).join("/");
                    }
                    break;
                }
              } else {
                this.cmds.push([
                  "out",
                  'No such file: "' + this.cmdLis[1] + '"',
                ]);
              }
            }
          }
          break;
        default:
          this.pushCmd(this.input);
          this.cmds.push(["out", 'Unknown command: "' + this.input + '"']);
          break;
      }
      this.input = "";
    },
    autoComplete() {
      const command = this.cmdLis[0];
      if (!command) {
        this.pushCmd("");
        this.cmds.push(["out", 'type "help" to see helps']);
        this.input = "";
      } else if (command === "cd") {
        const needComplete = this.cmdLis[1];
        const dirs = [];
        if (needComplete) {
          for (const d of this.dirsNow) {
            if (
              d.name.length >= needComplete.length &&
              d.name.startsWith(needComplete)
            ) {
              dirs.push(d.name);
            }
          }
        } else {
          dirs.push(...this.dirsNow.map((v) => v.name));
        }
        if (dirs.length > 0) {
          if (dirs.length === 1) {
            this.input = "cd " + dirs[0];
          } else {
            this.pushCmd(this.input);
            this.cmds.push(["out", dirs.join("\t")]);
          }
        }
      } else if (command === "xdg-open") {
        const needComplete = this.cmdLis[1];
        const dirs = [];
        if (needComplete) {
          for (const d of this.notDirsNow) {
            if (
              d.name.length >= needComplete.length &&
              d.name.startsWith(needComplete)
            ) {
              dirs.push(d.name);
            }
          }
        } else {
          dirs.push(...this.notDirsNow.map((v) => v.name));
        }
        if (dirs.length > 0) {
          if (dirs.length === 1) {
            this.input = "xdg-open " + dirs[0];
          } else {
            this.pushCmd(this.input);
            this.cmds.push(["out", dirs.join("\t")]);
          }
        }
      } else if (this.cmdLis.length === 1) {
        if (command === "c") {
          this.pushCmd("");
          this.cmds.push(["out", "cd\tclear"]);
        } else if (command === "p") {
          this.pushCmd("");
          this.cmds.push(["out", "poweroff\tpwd"]);
        } else if (["h", "he", "hel", "help"].includes(command)) {
          this.input = "help ";
        } else if (["l", "ls"].includes(command)) {
          this.input = "ls ";
        } else if (["cl", "cle", "clea", "clear"].includes(command)) {
          this.input = "clear ";
        } else if (["pw", "pwd"].includes(command)) {
          this.input = "pwd ";
        } else if (command === "cd") {
          const needComplete = this.cmdLis[1];
          console.log(needComplete);
          if (needComplete) {
            const dirs = [];
            for (const d of this.dirsNow) {
              if (
                d.name.length >= needComplete &&
                d.name.startsWith(needComplete)
              ) {
                dirs.push(d.name);
              }
            }
            console.log(dirs);
          }
        } else if (
          ["r", "re", "reb", "rebo", "reboo", "reboot"].includes(command)
        ) {
          this.input = "reboot ";
        } else if (
          [
            "po",
            "pow",
            "powe",
            "power",
            "powero",
            "powerof",
            "poweroff",
          ].includes(command)
        ) {
          this.input = "poweroff ";
        } else if (
          [
            "x",
            "xd",
            "xdg",
            "xdg-",
            "xdg-o",
            "xdg-op",
            "xdg-ope",
            "xdg-open",
          ].includes(command)
        ) {
          this.input = "xdg-open ";
        }
      }
    },
    upCmd() {
      if (this.hisIdx === -1) {
        this.hisIdx = this.history.length - 1;
      } else if (this.hisIdx > 0) {
        this.hisIdx--;
      }
      if (this.history.length && this.hisIdx >= 0) {
        this.input = this.history[this.hisIdx];
      }
    },
    downCmd() {
      if (this.hisIdx === -1) {
        this.hisIdx = this.history.length - 1;
      } else if (this.hisIdx < this.history.length - 1) {
        this.hisIdx++;
      }
      if (this.history.length && this.hisIdx < this.history.length) {
        this.input = this.history[this.hisIdx];
      }
    },
  },
});
</script>

<style scoped lang="scss">
.terminal {
  width: 100%;
  height: 100%;
  background: #1e2229;
  font-size: 0.75rem;
  color: white;
  padding-bottom: 0.6rem;
  > p {
    padding: 0.5rem;
    font-size: 0.8rem;
  }
  > div {
    display: flex;
    align-items: center;
    padding-top: 0.4rem;
    flex-wrap: wrap;
  }
  .header {
    word-break: keep-all;
    white-space: nowrap;
    flex-shrink: 0;
    color: #59a850;
    margin: 0 0.3rem;
    > span {
      color: white;
    }
  }
  .content {
    &.cmd {
      color: #13cba8;
    }

    &.out {
      width: calc(100% - 1.2rem);
      padding: 0 0.6rem;
      white-space: pre;
      :deep(span) {
        color: #44bbff;
      }
      :deep(p) {
        display: inline-block;
        width: 7.5rem;
        color: #ffce79;
      }
    }
  }
  input {
    background: transparent;
    flex-grow: 1;
    outline: none;
    border: none;
    color: white;
    font-size: 0.75rem;
  }
}
</style>

// src/components/apps/Terminal.tsx
import { useState, useRef, useEffect } from 'react';
import { dolphinFiles, typeFile } from '@/utils/filesystem';
import { useDesktopStore } from '@/store/useDesktopStore';

export const Terminal = () => {
  const [input, setInput] = useState('');
  const [history, setHistory] = useState<string[]>([]);
  const [output, setOutput] = useState<{ type: 'cmd' | 'out', content: string, dir?: string }[]>([]);
  const [dir, setDir] = useState<string[]>([]); // Empty = Home
  const inputRef = useRef<HTMLInputElement>(null);
  const bottomRef = useRef<HTMLDivElement>(null);
  const { openApp, setAppParams } = useDesktopStore();

  const dirStr = dir.length ? dir.join('/') : '~';

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      processCmd();
    }
  };

  const getFilesAtCurrentPath = (): typeFile[] => {
      let current = dolphinFiles;
      for (const p of dir) {
          const found = current.find(f => f.name === p && f.isDir);
          if (found && found.sub) {
              current = found.sub;
          } else {
              return [];
          }
      }
      return current;
  };

  const processCmd = () => {
    if (!input.trim()) {
        setOutput([...output, { type: 'cmd', content: '', dir: dirStr }]);
        setInput('');
        return;
    }

    const cmd = input.trim();
    const parts = cmd.split(/\s+/);
    const newOutput: { type: 'cmd' | 'out', content: string, dir?: string }[] = [...output, { type: 'cmd', content: cmd, dir: dirStr }];

    switch (parts[0]) {
      case 'help':
        newOutput.push({ type: 'out', content: 'ls - list files\ncd <dir> - change directory\nclear - clear screen\npwd - print working directory\nxdg-open <file> - open file' });
        break;
      case 'ls':
        const files = getFilesAtCurrentPath();
        newOutput.push({ type: 'out', content: files.map(f => f.isDir ? f.name + '/' : f.name).join('  ') });
        break;
      case 'pwd':
        newOutput.push({ type: 'out', content: `/home/hitu/${dirStr === '~' ? '' : dirStr}` });
        break;
      case 'cd':
        if (!parts[1] || parts[1] === '~') {
            setDir([]);
        } else if (parts[1] === '..') {
            setDir(dir.slice(0, -1));
        } else {
            const target = parts[1];
            const currentFiles = getFilesAtCurrentPath();
            const found = currentFiles.find(f => f.name === target && f.isDir);
            if (found) {
                setDir([...dir, target]);
            } else {
                newOutput.push({ type: 'out', content: `cd: ${target}: No such directory` });
            }
        }
        break;
      case 'xdg-open':
        if (!parts[1]) {
            newOutput.push({ type: 'out', content: 'xdg-open: missing file operand' });
        } else {
            const target = parts[1];
            const currentFiles = getFilesAtCurrentPath();
            const file = currentFiles.find(f => f.name === target && !f.isDir);
            if (file) {
                const filepath = [...dir, file.name].join('/');
                if (file.mime.startsWith('image/')) {
                    setAppParams('image-viewer', { filepath });
                    openApp('image-viewer');
                } else if (file.mime.startsWith('audio/')) {
                    setAppParams('music', { filepath });
                    openApp('music');
                } else if (file.mime === 'text/markdown') {
                    setAppParams('gedit', { filepath });
                    openApp('gedit');
                } else {
                     newOutput.push({ type: 'out', content: `xdg-open: no application for ${file.mime}` });
                }
            } else {
                newOutput.push({ type: 'out', content: `xdg-open: ${target}: No such file` });
            }
        }
        break;
      case 'clear':
        setOutput([]);
        setInput('');
        return;
      default:
        newOutput.push({ type: 'out', content: `Unknown command: ${parts[0]}` });
    }

    setOutput(newOutput);
    setHistory([...history, cmd]);
    setInput('');
  };

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [output]);

  return (
    <div className="w-full h-full bg-[#1e2229] text-white p-2 font-mono text-xs overflow-auto" onClick={() => inputRef.current?.focus()}>
      <p className="mb-2 text-gray-400">{`> Enjoy the fake terminal 😆.`}</p>
      
      {output.map((line, i) => (
        <div key={i} className="mb-1">
          {line.type === 'cmd' && (
            <span className="text-[#59a850] mr-2">[hitu@manjaro <span className="text-white">{line.dir}</span>]$</span>
          )}
          <span className={line.type === 'cmd' ? 'text-[#13cba8]' : 'text-[#44bbff] whitespace-pre-wrap'}>{line.content}</span>
        </div>
      ))}

      <div className="flex items-center">
         <span className="text-[#59a850] mr-2 flex-shrink-0">[hitu@manjaro <span className="text-white">{dirStr}</span>]$</span>
         <input 
           ref={inputRef}
           value={input}
           onChange={e => setInput(e.target.value)}
           onKeyDown={handleKeyDown}
           className="bg-transparent outline-none border-none flex-grow text-white"
           autoFocus
         />
      </div>
      <div ref={bottomRef} />
    </div>
  );
};
